src/Entity/Evaluation.php
<?php

namespace App\Entity;

use App\Repository\EvaluationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EvaluationRepository::class)]
class Evaluation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_client = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_client = null;

    #[ORM\Column(length: 255)]
    private ?string $avis_client = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_eval = null;

    #[ORM\ManyToOne(inversedBy: 'evaluations')]
    private ?Mecanicien $mecanicien = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->nom_client;
    }

    public function setNomClient(string $nom_client): static
    {
        $this->nom_client = $nom_client;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->prenom_client;
    }

    public function setPrenomClient(string $prenom_client): static
    {
        $this->prenom_client = $prenom_client;

        return $this;
    }

    public function getAvisClient(): ?string
    {
        return $this->avis_client;
    }

    public function setAvisClient(string $avis_client): static
    {
        $this->avis_client = $avis_client;

        return $this;
    }

    public function getDateEval(): ?\DateTimeInterface
    {
        return $this->date_eval;
    }

    public function setDateEval(\DateTimeInterface $date_eval): static
    {
        $this->date_eval = $date_eval;

        return $this;
    }

    public function getMecanicien(): ?Mecanicien
    {
        return $this->mecanicien;
    }

    public function setMecanicien(?Mecanicien $mecanicien): static
    {
        $this->mecanicien = $mecanicien;

        return $this;
    }
}

src/Controller/EvaluationFrontController.php
<?php

namespace App\Controller;

use App\Entity\Evaluation;
use App\Form\Evaluation1Type;
use App\Repository\EvaluationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Joli\JoliNotif\Notification;
use Joli\JoliNotif\NotifierFactory;

#[Route('/evaluation_front')]
class EvaluationFrontController extends AbstractController
{
    #[Route('/', name: 'app_evaluation_front_index', methods: ['GET'])]
    public function index(EvaluationRepository $evaluationRepository): Response
    {
        return $this->render('evaluation_front/index.html.twig', [
            'evaluations' => $evaluationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_evaluation_front_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evaluation = new Evaluation();
        $form = $this->createForm(Evaluation1Type::class, $evaluation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evaluation);
            $entityManager->flush();

              // Create a Notifier
         $notifier = NotifierFactory::create();
 
         // Create your notification
         $notification =
             (new Notification())
             ->setTitle('Notification!')
             ->setBody('Votre Evaluation va étre prise en considération !')
            
         ;
         
         // Send it
         $notifier->send($notification);
         return $this->redirectToRoute('app_evaluation_front_new', [], Response::HTTP_SEE_OTHER);  
                     
                 }

        return $this->renderForm('evaluation_front/new.html.twig', [
            'evaluation' => $evaluation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evaluation_front_show', methods: ['GET'])]
    public function show(Evaluation $evaluation): Response
    {
        return $this->render('evaluation_front/show.html.twig', [
            'evaluation' => $evaluation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_evaluation_front_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Evaluation $evaluation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Evaluation1Type::class, $evaluation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_evaluation_front_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evaluation_front/edit.html.twig', [
            'evaluation' => $evaluation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_evaluation_front_delete', methods: ['POST'])]
    public function delete(Request $request, Evaluation $evaluation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evaluation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($evaluation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_evaluation_front_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evaluation_front/_delete_form.html.twig
<form method="post" action="{{ path('app_evaluation_front_delete', {'id': evaluation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evaluation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evaluation_front/edit.html.twig
{% extends 'client/base-client.html.twig' %}

{% block body %}
    <h1>Edit Evaluation</h1>

    {{ include('evaluation_front/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_evaluation_front_index') }}">back to list</a>

    {{ include('evaluation_front/_delete_form.html.twig') }}
{% endblock %}

templates/evaluation_front/index.html.twig
{% extends 'client/base-client.html.twig' %}
{% block body %}
    <h1>Les Evaluations</h1>
    <h2>Vous pouvez faire votre évaluation ici!</h2>
    <a href="{{ path('app_evaluation_front_new') }}">Create new</a>
{% endblock %}

templates/evaluation_front/new.html.twig
{% extends 'client/base-client.html.twig' %}

{% block body %}
    <h1>Create new Evaluation</h1>

    {{ include('evaluation_front/_form.html.twig') }}

    <a href="{{ path('app_evaluation_front_index') }}">back to list</a>
{% endblock %}

templates/evaluation_front/show.html.twig
{% extends 'client/base-client.html.twig' %}

{% block body %}
    <h1>Evaluation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evaluation.id }}</td>
            </tr>
            <tr>
                <th>Nom_client</th>
                <td>{{ evaluation.nomClient }}</td>
            </tr>
            <tr>
                <th>Prenom_client</th>
                <td>{{ evaluation.prenomClient }}</td>
            </tr>
            <tr>
                <th>Avis_client</th>
                <td>{{ evaluation.avisClient }}</td>
            </tr>
            <tr>
                <th>Date_eval</th>
                <td>{{ evaluation.dateEval ? evaluation.dateEval|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_evaluation_front_index') }}">back to list</a>

    <a href="{{ path('app_evaluation_front_edit', {'id': evaluation.id}) }}">edit</a>

    {{ include('evaluation_front/_delete_form.html.twig') }}
{% endblock %}